#!/usr/bin/bash

export DISPLAY=:0
USER=$(ls /home/)
export XAUTHORITY="/home/$USER/.Xauthority"
while true; do
	killall syndaemon
	modprobe -r i2c_hid_acpi
	modprobe i2c_hid_acpi
	modprobe -r idma64
	modprobe idma64
	sleep 1
	synclient TapButton1=1
	synclient TapButton2=3
	synclient TapButton3=2
	syndaemon -i 0.4 -d
	sleep 120
done
